### ISSUE TITLE
是否可以支持监听App globalData的数据

### ISSUE THREAD

**Issue by xmsz** [hendiko/miniprogrampatch#2]
在页面的使用中，会用到App.js里globalData的数据
请问该如何实现监听这些数据

**Comment by hendiko** [comment]
@xmsz  app.globalData 里的数据并不在监听范围内，如果你需要监听这部分数据的变化，可以自己在 app 对象上封装一个类似 setGlobalData 的方法，在这个方法中实现数据检查，然后使用发布订阅的方式来实现数据监听。

> PS: [armor-pubsub](https://github.com/hendiko/armor-pubsub)
