### ISSUE TITLE
app.js里全局引入，别的页面没有改动的情况下，首页报错Cannot read property 'length' of undefined;

### ISSUE THREAD

**Issue by Josie-ljw** [hendiko/miniprogrampatch#4]
![image](https://user-images.githubusercontent.com/20377604/55697733-54700d80-59f5-11e9-8b5b-24c1bab4bb62.png)
![image](https://user-images.githubusercontent.com/20377604/55697748-6b166480-59f5-11e9-8caf-3534d49b131f.png)

**Comment by hendiko** [comment]
@Josie-ljw 请检查一下你引用的是否是最新版本的 miniprogrampatch(最新版本为 v1.1.10)。

**Comment by Josie-ljw** [comment]
> @Josie-ljw 请检查一下你引用的是否是最新版本的 miniprogrampatch(最新版本为 v1.1.10)。

啊啊啊我用的老版本，报错没有了感谢~

**Comment by hendiko** [comment]
@Josie-ljw 不客气。
