### ISSUE TITLE
当数组结构里的某个属性发生变化，则不生效啊，可能有bug插件。

### ISSUE THREAD

**Issue by tianyazjq** [hendiko/miniprogrampatch#5]
![image](https://user-images.githubusercontent.com/5754329/56335203-2d23f800-61ce-11e9-953e-57256bdb254a.png)
![image](https://user-images.githubusercontent.com/5754329/56335208-33b26f80-61ce-11e9-8025-f8589518ece6.png)
![image](https://user-images.githubusercontent.com/5754329/56335222-3f059b00-61ce-11e9-84ad-0e55f3fe45ec.png)
当数组结构里的某个属性发生变化，则不生效啊，可能有bug插件。

**Comment by tianyazjq** [comment]
![image](https://user-images.githubusercontent.com/5754329/56335267-68262b80-61ce-11e9-9133-8709fef52220.png)
这个 属性来回切换发生变化，computed一点反应也没有哒

**Comment by hendiko** [comment]
你不能直接在`微信开发工具` - `调试器` 的 `AppData` 面板下面直接修改 `selected` 字段的值，这样肯定不会触发 computed 重新计算啊。

建议你在页面上做一个按钮，然后在处理点击事件中通过 `setData` 来触发数据更新。

根据你的数据结构，点击事件处理方法类似以下代码：

```js
onTap(e) {
   let {index} = e.currentTarget.dataset;
   let {resultList} = this.data;
   let selected = resultList[index]['selected'];
  // 更新数据
   this.$setData({[`resultList[${index}].selected`]: !selected})
}

```

**Comment by tianyazjq** [comment]
> 你不能直接在`微信开发工具` - `调试器` 的 `AppData` 面板下面直接修改 `selected` 字段的值，这样肯定不会触发 computed 重新计算啊。
> 
> 建议你在页面上做一个按钮，然后在处理点击事件中通过 `setData` 来触发数据更新。
> 
> 根据你的数据结构，点击事件处理方法类似以下代码：
> 
> ```js
> onTap(e) {
>    let {index} = e.currentTarget.dataset;
>    let {resultList} = this.data;
>    let selected = resultList[index]['selected'];
>   // 更新数据
>    this.$setData({[`resultList[${index}].selected`]: !selected})
> }
> ```

这个我不是在开发者工具里直接去修改值的，那个是我截图给你看的，页面操作setData改变值的。你可 以试一下类似这种的data:{
   testArr:[
    {a:1,b:2},
   {a:2,b:3}
]
}
这种的结构的，里面数组值或者属性发生改变，不触发computed的，直接object,或者aa:1,这种的是可以的。
testArr这种的数组，值发生变化，不会触发computed

**Comment by hendiko** [comment]
@tianyazjq 我猜你想表达可能是以下这种应用场景：

```js
let {testArr} = this.data;
let item = testArr[0]
testArr['a'] = 2;
this.setData({testArr})
```

在这种场景下 miniprogrampatch 不会重新计算 computed 属性，因为 `this.setData` 方法设置的 `testArr` 值仍然是之前那个对象（数组对象）。



有两个方法可以触发 computed 计算：

方法一：设置一个新的对象

```js
this.setData({testArr: [...testArr]})
```

方法二：使用路径设置 `a` 的值

```js
this.setData({'testArr[0].a': 2})
```

> 关于 `setData`  更新数据的行为，miniprogrampatch 和微信小程序的默认行为有一些不一致。
> 从微信小程序 2.6.6 版本开始在组件中提供的 `observer` 配置来看，微信小程序看起来每次调用 `setData` 都会触发 `observer` 的回调函数，哪怕实际上数据原封不动未做任何修改。 
> 而 miniprogrampatch 调用 `setData`  时首先会检查数据是否发生变化，再决定是否要触发相关的重新计算。

**Comment by tianyazjq** [comment]
好的，谢谢大大的思路，非常感谢！！
